### ISSUE TITLE
atomicAdd problem?

### ISSUE THREAD

**Issue by pedritolo** [cair/PyTsetlinMachineCUDA#5]
Hi, sorry to keep pestering you with these.

I'm probably missing something obvious, but I suspect the following may be a problem:
In the update method, you have 2 "for (int i = index; i < CLASSES*CLAUSES; i += stride)" loops.
The 1st loop does atomicAdd on the class_sum, and the 2nd reads from the class_sum. 
The problem is that when reading the class_sum (on the 2nd loop), there's no guarantee that the other threads responsible for updating the class_sum for that particular [class/example] have also left the 1st loop. In other words, class_sum may still be under construction (and other buffers as well, like global_clause_patch or clause_output).

Anyway, thanks for the feedback on my previous issues

**Comment by olegranmo** [comment]
No problem @pedritolo - happy to discuss! You are again right. This is by design for increased learning speed. Due to the robustness of Tsetlin Automata learning and the interaction between the Tsetlin Automata teams, they cope with working with the partially calculated or slightly outdated class_sum's. Actually, Tsetlin machine learning seems to be inherently fault-tolerant: https://www.staff.ncl.ac.uk/rishad.shafik/files/2020/05/isvlsi2020_Shafik.pdf, https://youtu.be/N-wkgibJAZE.
Each clause may even pick examples randomly by itself instead of the current sequential order, and the learning still converges in many cases (however, at a slower speed due to less effective memory management on the GPU-side). There is also a fully synchronized CUDA-implementation here: https://github.com/cair/fast-tsetlin-machine-in-cuda-with-imdb-demo. This is also quite fast but learns 2.5x slower than the more asynchronous version implemented here (on IMDb).
