### ISSUE TITLE
Parallel vs CUDA Version

### ISSUE THREAD

**Issue by impulsecorp** [cair/PyTsetlinMachineCUDA#7]
What is the advantage of using this new CUDA version over the parallel version (https://github.com/cair/pyTsetlinMachineParallel)?
I understand how your new decentralized TM learning algorithm is a breakthrough, but how does it compare with the speed of the parallel version? Your paper shows 2x-50x GPU speed vs a single core computer, but if I used a 64 core non-GPU server, wouldn't that be faster than the GPU?

**Comment by olegranmo** [comment]
Hi @impulsecorp! The two implementations differ in how they have been parallelized. https://github.com/cair/pyTsetlinMachineParallel uses one thread per example and has been tested with up to 24 cores. The key in that implementation is to lock the clause you are going to update so that only one thread at a time update the clause. That locking mechanism was a big bottleneck on the GPU, so we instead figured out how to avoid locking, using one thread per clause. Both have comparable speed, but we have not tested yet how the first one scales with number of cores. Each core on the CPU is very fast, so I suspect 64 cores would be quite powerful.
